/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package requestparser;

import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;

public class App {

    public static void main(String[] args) {
        Client client = new Client("severa");
        System.out.println(client.login());
    }
}
